/**
 * Phase 1 school management system — multi-page + API + file-backed store + tests.
 * Node stdlib only (no npm install). Phase 2/3 modules are planned, not faked.
 */

function htmlPage(title: string, active: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} · School Manager</title>
  <link rel="stylesheet" href="/css/app.css" />
</head>
<body>
  <div id="nav"></div>
  <main class="wrap">
    <h1>${title}</h1>
    <div id="flash" class="flash hidden"></div>
    ${body}
  </main>
  <script src="/js/api.js"></script>
  <script src="/js/auth.js"></script>
  <script src="/js/nav.js"></script>
  <script>window.__PAGE__ = ${JSON.stringify(active)};</script>
</body>
</html>
`;
}

export function schoolManagementProjectFiles(): Array<{ path: string; content: string }> {
  return [
    {
      path: "README.md",
      content: `# School Management System

Phased full application generated by Personal AI Orchestrate.

## Status
Phase 1 is implemented. Phases 2–3 are planned, not implemented.
This is **PARTIAL** relative to a complete school platform — not a one-page demo.

## Phase 1 (implemented)
- Authentication (login, logout, signed session)
- Roles: Admin, Teacher, Student, Parent (enforced on the **API**, not only the UI)
- Dashboards per role
- Student management (list, profile, create, edit)
- Teacher management (list, profile, create, edit)
- Attendance (dashboard, mark, history) — teachers can mark; students cannot
- Classes (list, details)
- File-backed JSON store (\`data/db.json\`) — not a hardcoded production array
- Loading, empty, and error states on list pages
- Tests for RBAC, auth, students, attendance authorization

## Phase 2 (not in this delivery)
Exams, fees, timetable, assignments

## Phase 3 (not in this delivery)
Reports, notifications, settings, hardening

## Run
\`\`\`bash
node src/server.js
\`\`\`
Open http://localhost:3456/login.html

## Test
\`\`\`bash
node --test test/
\`\`\`

## Demo accounts (SEED_DATA)
| Role    | Email                 | Password   |
|---------|-----------------------|------------|
| Admin   | admin@school.local    | admin123   |
| Teacher | teacher@school.local  | teacher123 |
| Student | student@school.local  | student123 |
| Parent  | parent@school.local   | parent123  |

SEED_DATA is for local demo only. Persistence after login is the JSON store, not in-memory-only mocks.

## Honesty
- CODE_EXECUTION_SUCCESS means the server started or tests ran.
- PROJECT_STATUS is PARTIAL until Phases 2–3 exist.
- Backend authorization is required: hiding a button is not access control.
`,
    },
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "school-management",
          version: "0.2.0",
          private: true,
          type: "module",
          scripts: {
            start: "node src/server.js",
            test: "node --test test/",
          },
        },
        null,
        2,
      ),
    },
    {
      path: "schema/schema.sql",
      content: `-- Logical schema (file-backed JSON implements these collections)
-- Persistence: data/db.json (workspace durable store)

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('Admin','Teacher','Student','Parent')),
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

CREATE TABLE students (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT,
  grade TEXT,
  class_id TEXT REFERENCES classes(id),
  created_at TEXT NOT NULL
);
CREATE INDEX idx_students_class ON students(class_id);

CREATE TABLE teachers (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT,
  subject TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE classes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  section TEXT,
  grade TEXT,
  teacher_id TEXT REFERENCES teachers(id)
);

CREATE TABLE enrollments (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id),
  class_id TEXT NOT NULL REFERENCES classes(id),
  UNIQUE (student_id, class_id)
);

CREATE TABLE attendance (
  id TEXT PRIMARY KEY,
  student_id TEXT NOT NULL REFERENCES students(id),
  class_id TEXT,
  date TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('present','absent','late')),
  marked_by TEXT NOT NULL REFERENCES users(id),
  UNIQUE (student_id, date)
);
CREATE INDEX idx_attendance_date ON attendance(date);
CREATE INDEX idx_attendance_student ON attendance(student_id);
`,
    },
    {
      path: "database/migrations/001_init.sql",
      content: `-- Applied conceptually on first store seed. See schema/schema.sql.\n`,
    },
    {
      path: "src/store.js",
      content: `import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";
import { hashPassword } from "./auth.js";

const root = dirname(fileURLToPath(import.meta.url));
export const DEFAULT_DB_PATH = process.env.DB_PATH || join(root, "../data/db.json");

function emptyData() {
  return {
    users: [],
    students: [],
    teachers: [],
    classes: [],
    enrollments: [],
    attendance: [],
    sessions: [],
  };
}

export function seedData() {
  const data = emptyData();
  const admin = {
    id: randomUUID(),
    email: "admin@school.local",
    name: "Ada Admin",
    role: "Admin",
    passwordHash: hashPassword("admin123"),
    createdAt: new Date().toISOString(),
  };
  const teacherUser = {
    id: randomUUID(),
    email: "teacher@school.local",
    name: "Tom Teacher",
    role: "Teacher",
    passwordHash: hashPassword("teacher123"),
    createdAt: new Date().toISOString(),
  };
  const studentUser = {
    id: randomUUID(),
    email: "student@school.local",
    name: "Sam Student",
    role: "Student",
    passwordHash: hashPassword("student123"),
    createdAt: new Date().toISOString(),
  };
  const parentUser = {
    id: randomUUID(),
    email: "parent@school.local",
    name: "Pat Parent",
    role: "Parent",
    passwordHash: hashPassword("parent123"),
    createdAt: new Date().toISOString(),
  };
  data.users.push(admin, teacherUser, studentUser, parentUser);
  const klass = { id: randomUUID(), name: "Grade 8", section: "A", grade: "8", teacherId: null };
  const teacher = {
    id: randomUUID(),
    userId: teacherUser.id,
    firstName: "Tom",
    lastName: "Teacher",
    email: teacherUser.email,
    subject: "Mathematics",
    createdAt: new Date().toISOString(),
  };
  klass.teacherId = teacher.id;
  const student = {
    id: randomUUID(),
    userId: studentUser.id,
    firstName: "Sam",
    lastName: "Student",
    email: studentUser.email,
    grade: "8",
    classId: klass.id,
    createdAt: new Date().toISOString(),
  };
  data.teachers.push(teacher);
  data.classes.push(klass);
  data.students.push(student);
  data.enrollments.push({ id: randomUUID(), studentId: student.id, classId: klass.id });
  return data;
}

export function createStore(filePath) {
  const path = filePath || DEFAULT_DB_PATH;
  mkdirSync(dirname(path), { recursive: true });
  let data = emptyData();
  if (existsSync(path)) {
    try {
      data = JSON.parse(readFileSync(path, "utf8"));
    } catch {
      data = seedData();
    }
  } else {
    data = seedData();
  }
  function persist() {
    writeFileSync(path, JSON.stringify(data, null, 2));
  }
  persist();
  return {
    path,
    data,
    save: persist,
    all(name) {
      return data[name] || [];
    },
    get(name, id) {
      return (data[name] || []).find((r) => r.id === id) || null;
    },
    find(name, pred) {
      return (data[name] || []).find(pred) || null;
    },
    insert(name, row) {
      const rec = { id: row.id || randomUUID(), ...row };
      data[name].push(rec);
      persist();
      return rec;
    },
    update(name, id, patch) {
      const list = data[name];
      const i = list.findIndex((r) => r.id === id);
      if (i < 0) return null;
      list[i] = { ...list[i], ...patch, id };
      persist();
      return list[i];
    },
    remove(name, id) {
      const before = data[name].length;
      data[name] = data[name].filter((r) => r.id !== id);
      persist();
      return data[name].length < before;
    },
  };
}
`,
    },
    {
      path: "src/auth.js",
      content: `import { scryptSync, randomBytes, timingSafeEqual, createHmac } from "node:crypto";

const SECRET = process.env.AUTH_SECRET || "dev-secret-change-me";

export function hashPassword(password, salt) {
  const s = salt || randomBytes(16).toString("hex");
  const hash = scryptSync(String(password), s, 32).toString("hex");
  return s + ":" + hash;
}

export function verifyPassword(password, stored) {
  if (!stored || !stored.includes(":")) return false;
  const parts = stored.split(":");
  const s = parts[0];
  const hash = parts[1];
  const check = scryptSync(String(password), s, 32);
  const a = Buffer.from(hash, "hex");
  if (a.length !== check.length) return false;
  return timingSafeEqual(a, check);
}

export function signToken(payload) {
  const body = Buffer.from(
    JSON.stringify({ ...payload, exp: Date.now() + 24 * 60 * 60 * 1000 }),
  ).toString("base64url");
  const sig = createHmac("sha256", SECRET).update(body).digest("base64url");
  return body + "." + sig;
}

export function verifyToken(token) {
  if (!token || !token.includes(".")) return null;
  const i = token.lastIndexOf(".");
  const body = token.slice(0, i);
  const sig = token.slice(i + 1);
  const expected = createHmac("sha256", SECRET).update(body).digest("base64url");
  if (sig !== expected) return null;
  try {
    const payload = JSON.parse(Buffer.from(body, "base64url").toString("utf8"));
    if (!payload.exp || payload.exp < Date.now()) return null;
    return payload;
  } catch {
    return null;
  }
}

export function bearer(req) {
  const h = req.headers.authorization || req.headers.Authorization || "";
  if (typeof h === "string" && h.startsWith("Bearer ")) return h.slice(7);
  return null;
}
`,
    },
    {
      path: "src/rbac.js",
      content: `export const ROLES = ["Admin", "Teacher", "Student", "Parent"];

const PERMISSIONS = {
  Admin: [
    "manage_users",
    "manage_students",
    "manage_teachers",
    "manage_classes",
    "manage_attendance",
    "view_students",
    "view_teachers",
    "view_attendance",
    "view_dashboard",
  ],
  Teacher: [
    "manage_attendance",
    "view_students",
    "view_teachers",
    "view_attendance",
    "view_dashboard",
  ],
  Student: ["view_attendance", "view_dashboard", "view_own_profile"],
  Parent: ["view_attendance", "view_dashboard", "view_own_profile"],
};

export function canAccess(role, permission) {
  if (!ROLES.includes(role)) return false;
  return (PERMISSIONS[role] || []).includes(permission);
}

export function listPermissions(role) {
  return PERMISSIONS[role] || [];
}

export function requirePermission(user, permission) {
  if (!user || !canAccess(user.role, permission)) {
    const err = new Error("Forbidden");
    err.statusCode = 403;
    throw err;
  }
}
`,
    },
    {
      path: "src/routes.js",
      content: `import { readFileSync, existsSync, statSync } from "node:fs";
import { extname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import { hashPassword, verifyPassword, signToken, verifyToken, bearer } from "./auth.js";
import { listPermissions, requirePermission, ROLES } from "./rbac.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
};

function send(res, status, body, headers) {
  const payload = typeof body === "string" ? body : JSON.stringify(body);
  res.writeHead(status, {
    "Content-Type": typeof body === "string" ? "text/plain; charset=utf-8" : "application/json; charset=utf-8",
    ...(headers || {}),
  });
  res.end(payload);
}

function json(res, status, body) {
  send(res, status, body, { "Content-Type": "application/json; charset=utf-8" });
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => {
      const raw = Buffer.concat(chunks).toString("utf8");
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch {
        reject(Object.assign(new Error("Invalid JSON"), { statusCode: 400 }));
      }
    });
    req.on("error", reject);
  });
}

function parseUrl(req) {
  const u = new URL(req.url || "/", "http://localhost");
  return { pathname: u.pathname, searchParams: u.searchParams };
}

function currentUser(store, req) {
  const token = bearer(req);
  const payload = verifyToken(token);
  if (!payload) return null;
  return store.get("users", payload.userId);
}

function publicUser(u) {
  if (!u) return null;
  return { id: u.id, email: u.email, name: u.name, role: u.role };
}

function match(pathname, pattern) {
  const a = pathname.split("/").filter(Boolean);
  const b = pattern.split("/").filter(Boolean);
  if (a.length !== b.length) return null;
  const params = {};
  for (let i = 0; i < b.length; i++) {
    if (b[i].startsWith(":")) params[b[i].slice(1)] = decodeURIComponent(a[i]);
    else if (a[i] !== b[i]) return null;
  }
  return params;
}

function serveStatic(pathname, res) {
  let rel = pathname === "/" ? "/login.html" : pathname;
  const abs = normalize(join(publicDir, rel));
  if (!abs.startsWith(publicDir)) {
    json(res, 403, { error: "Forbidden" });
    return true;
  }
  if (!existsSync(abs) || !statSync(abs).isFile()) return false;
  const buf = readFileSync(abs);
  res.writeHead(200, { "Content-Type": MIME[extname(abs)] || "application/octet-stream" });
  res.end(buf);
  return true;
}

export function createHandler(store) {
  return async function handler(req, res) {
    try {
      const { pathname, searchParams } = parseUrl(req);
      const method = (req.method || "GET").toUpperCase();

      if (pathname === "/health") {
        return json(res, 200, { ok: true, roles: ROLES, project: "school-management" });
      }

      if (method === "POST" && pathname === "/api/auth/login") {
        const body = await readBody(req);
        const email = String(body.email || "").trim().toLowerCase();
        const password = String(body.password || "");
        if (!email || !password) return json(res, 400, { error: "email and password required" });
        const user = store.find("users", (u) => u.email.toLowerCase() === email);
        if (!user || !verifyPassword(password, user.passwordHash)) {
          return json(res, 401, { error: "Invalid credentials" });
        }
        const token = signToken({ userId: user.id, role: user.role });
        store.insert("sessions", { userId: user.id, token, createdAt: new Date().toISOString() });
        return json(res, 200, { token, user: publicUser(user) });
      }

      if (method === "POST" && pathname === "/api/auth/logout") {
        const token = bearer(req);
        if (token) {
          const sess = store.find("sessions", (s) => s.token === token);
          if (sess) store.remove("sessions", sess.id);
        }
        return json(res, 200, { ok: true });
      }

      const user = currentUser(store, req);

      if (method === "GET" && pathname === "/api/auth/me") {
        if (!user) return json(res, 401, { error: "Unauthorized" });
        return json(res, 200, { user: publicUser(user), permissions: listPermissions(user.role) });
      }

      if (pathname.startsWith("/api/") && !user) {
        return json(res, 401, { error: "Unauthorized" });
      }

      if (method === "GET" && pathname === "/api/dashboard") {
        requirePermission(user, "view_dashboard");
        const payload = {
          role: user.role,
          students: store.all("students").length,
          teachers: store.all("teachers").length,
          classes: store.all("classes").length,
          attendanceToday: store.all("attendance").filter((a) => a.date === new Date().toISOString().slice(0, 10)).length,
        };
        return json(res, 200, payload);
      }

      if (method === "GET" && pathname === "/api/students") {
        requirePermission(user, "view_students");
        return json(res, 200, { items: store.all("students") });
      }

      let m = match(pathname, "/api/students/:id");
      if (m && method === "GET") {
        requirePermission(user, "view_students");
        const row = store.get("students", m.id);
        if (!row) return json(res, 404, { error: "Not found" });
        return json(res, 200, row);
      }
      if (method === "POST" && pathname === "/api/students") {
        requirePermission(user, "manage_students");
        const body = await readBody(req);
        const firstName = String(body.firstName || "").trim();
        const lastName = String(body.lastName || "").trim();
        if (!firstName || !lastName) return json(res, 400, { error: "firstName and lastName required" });
        const row = store.insert("students", {
          firstName,
          lastName,
          email: String(body.email || "").trim(),
          grade: String(body.grade || "").trim(),
          classId: body.classId || null,
          createdAt: new Date().toISOString(),
        });
        return json(res, 201, row);
      }
      if (m && method === "PUT") {
        requirePermission(user, "manage_students");
        const body = await readBody(req);
        const row = store.update("students", m.id, {
          firstName: body.firstName,
          lastName: body.lastName,
          email: body.email,
          grade: body.grade,
          classId: body.classId,
        });
        if (!row) return json(res, 404, { error: "Not found" });
        return json(res, 200, row);
      }

      if (method === "GET" && pathname === "/api/teachers") {
        requirePermission(user, "view_teachers");
        return json(res, 200, { items: store.all("teachers") });
      }
      m = match(pathname, "/api/teachers/:id");
      if (m && method === "GET") {
        requirePermission(user, "view_teachers");
        const row = store.get("teachers", m.id);
        if (!row) return json(res, 404, { error: "Not found" });
        return json(res, 200, row);
      }
      if (method === "POST" && pathname === "/api/teachers") {
        requirePermission(user, "manage_teachers");
        const body = await readBody(req);
        const firstName = String(body.firstName || "").trim();
        const lastName = String(body.lastName || "").trim();
        if (!firstName || !lastName) return json(res, 400, { error: "firstName and lastName required" });
        const row = store.insert("teachers", {
          firstName,
          lastName,
          email: String(body.email || "").trim(),
          subject: String(body.subject || "").trim(),
          createdAt: new Date().toISOString(),
        });
        return json(res, 201, row);
      }
      if (m && method === "PUT") {
        requirePermission(user, "manage_teachers");
        const body = await readBody(req);
        const row = store.update("teachers", m.id, {
          firstName: body.firstName,
          lastName: body.lastName,
          email: body.email,
          subject: body.subject,
        });
        if (!row) return json(res, 404, { error: "Not found" });
        return json(res, 200, row);
      }

      if (method === "GET" && pathname === "/api/classes") {
        return json(res, 200, { items: store.all("classes") });
      }
      m = match(pathname, "/api/classes/:id");
      if (m && method === "GET") {
        const row = store.get("classes", m.id);
        if (!row) return json(res, 404, { error: "Not found" });
        const students = store.all("students").filter((s) => s.classId === row.id);
        return json(res, 200, { ...row, students });
      }

      if (method === "GET" && pathname === "/api/attendance") {
        requirePermission(user, "view_attendance");
        const date = searchParams.get("date");
        const studentId = searchParams.get("studentId");
        let items = store.all("attendance");
        if (date) items = items.filter((a) => a.date === date);
        if (studentId) items = items.filter((a) => a.studentId === studentId);
        return json(res, 200, { items });
      }
      if (method === "POST" && pathname === "/api/attendance") {
        requirePermission(user, "manage_attendance");
        const body = await readBody(req);
        const studentId = String(body.studentId || "");
        const date = String(body.date || "").slice(0, 10);
        const status = String(body.status || "");
        if (!studentId || !date || !["present", "absent", "late"].includes(status)) {
          return json(res, 400, { error: "studentId, date, status required" });
        }
        if (!store.get("students", studentId)) return json(res, 404, { error: "Student not found" });
        const existing = store.find("attendance", (a) => a.studentId === studentId && a.date === date);
        const rec = existing
          ? store.update("attendance", existing.id, { status, markedBy: user.id })
          : store.insert("attendance", {
              studentId,
              classId: body.classId || null,
              date,
              status,
              markedBy: user.id,
            });
        return json(res, 200, rec);
      }

      if (serveStatic(pathname, res)) return;
      return json(res, 404, { error: "not found" });
    } catch (err) {
      const code = err && err.statusCode ? err.statusCode : 500;
      return json(res, code, { error: err.message || "error" });
    }
  };
}
`,
    },
    {
      path: "src/server.js",
      content: `import http from "node:http";
import { createStore } from "./store.js";
import { createHandler } from "./routes.js";
import { ROLES } from "./rbac.js";

export function startServer(port, dbPath) {
  const store = createStore(dbPath);
  const server = http.createServer(createHandler(store));
  return new Promise((resolve) => {
    server.listen(port, () => {
      const addr = server.address();
      resolve({ server, port: typeof addr === "object" && addr ? addr.port : port, store });
    });
  });
}

const PORT = Number(process.env.PORT || 3456);
if (process.argv[1] && process.argv[1].endsWith("server.js")) {
  startServer(PORT).then(({ port }) => {
    console.log("CODE_EXECUTION_SUCCESS=true");
    console.log("school_management listening port=" + port);
    console.log("roles=" + ROLES.join(","));
  });
}
`,
    },
    {
      path: "public/css/app.css",
      content: `*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;background:#0b1220;color:#e8eef7;line-height:1.5}
a{color:#7dd3fc}nav{display:flex;flex-wrap:wrap;gap:.75rem;padding:1rem 6vw;background:#0f172a;border-bottom:1px solid #1e293b}
nav a{text-decoration:none;color:#94a3b8}nav a.active,nav a:hover{color:#e8eef7}
.wrap{padding:1.5rem 6vw 3rem;max-width:960px}h1{font-size:1.5rem}
.card{background:#111827;border:1px solid #1f2937;border-radius:.75rem;padding:1rem;margin:.75rem 0}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.75rem}
label{display:block;margin:.5rem 0 .25rem;color:#94a3b8;font-size:.85rem}
input,select,button{font:inherit}input,select{width:100%;padding:.55rem .7rem;border-radius:.5rem;border:1px solid #334155;background:#0b1220;color:#e8eef7}
button,.btn{display:inline-block;margin-top:.75rem;padding:.55rem 1rem;border-radius:.5rem;border:0;background:#38bdf8;color:#0b1220;font-weight:600;cursor:pointer;text-decoration:none}
button.secondary{background:#1e293b;color:#e8eef7}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:.5rem;border-bottom:1px solid #1e293b}
.muted{color:#94a3b8}.error{color:#fca5a5}.flash{padding:.75rem;border-radius:.5rem;margin-bottom:1rem}
.flash.err{background:#7f1d1d}.flash.ok{background:#14532d}.hidden{display:none}
.empty{padding:2rem;text-align:center;color:#64748b}
@media(max-width:640px){nav{font-size:.85rem}.wrap{padding:1rem}}
`,
    },
    {
      path: "public/js/api.js",
      content: `window.api = async function api(path, opts) {
  const token = localStorage.getItem("sms_token");
  const headers = Object.assign({ "Content-Type": "application/json" }, (opts && opts.headers) || {});
  if (token) headers.Authorization = "Bearer " + token;
  const res = await fetch(path, {
    method: (opts && opts.method) || "GET",
    headers,
    body: opts && opts.body ? JSON.stringify(opts.body) : undefined,
  });
  let data = {};
  try { data = await res.json(); } catch (e) { data = {}; }
  if (res.status === 401 && !path.includes("/auth/login")) {
    localStorage.removeItem("sms_token");
    location.href = "/login.html";
  }
  return { ok: res.ok, status: res.status, data };
};
window.showFlash = function (msg, kind) {
  const el = document.getElementById("flash");
  if (!el) return;
  el.textContent = msg;
  el.className = "flash " + (kind || "ok");
};
window.setLoading = function (id, on) {
  const el = document.getElementById(id);
  if (!el) return;
  el.textContent = on ? "Loading…" : "";
};
`,
    },
    {
      path: "public/js/auth.js",
      content: `window.requireAuth = async function requireAuth() {
  const token = localStorage.getItem("sms_token");
  if (!token) { location.href = "/login.html"; return null; }
  const r = await window.api("/api/auth/me");
  if (!r.ok) { location.href = "/login.html"; return null; }
  window.__USER__ = r.data.user;
  return r.data.user;
};
window.logout = async function logout() {
  await window.api("/api/auth/logout", { method: "POST" });
  localStorage.removeItem("sms_token");
  location.href = "/login.html";
};
`,
    },
    {
      path: "public/js/nav.js",
      content: `(async function () {
  const nav = document.getElementById("nav");
  if (!nav) return;
  if (location.pathname.endsWith("login.html") || location.pathname === "/") {
    nav.innerHTML = "<nav><strong>School Manager</strong></nav>";
    return;
  }
  const user = await window.requireAuth();
  if (!user) return;
  const page = window.__PAGE__ || "";
  const links = [
    ["dashboard.html", "Dashboard", "dashboard"],
    ["students.html", "Students", "students"],
    ["teachers.html", "Teachers", "teachers"],
    ["attendance.html", "Attendance", "attendance"],
    ["classes.html", "Classes", "classes"],
  ];
  const items = links
    .map(function (l) {
      const cls = page.indexOf(l[2]) >= 0 ? "active" : "";
      return '<a class="' + cls + '" href="/' + l[0] + '">' + l[1] + "</a>";
    })
    .join("");
  nav.innerHTML =
    "<nav><strong>School Manager</strong>" +
    items +
    '<span class="muted">' +
    user.name +
    " · " +
    user.role +
    '</span><a href="#" id="logout">Logout</a></nav>';
  document.getElementById("logout").onclick = function (e) {
    e.preventDefault();
    window.logout();
  };
})();
`,
    },
    {
      path: "public/login.html",
      content: htmlPage(
        "Login",
        "login",
        `<form class="card" id="f">
  <label>Email</label><input name="email" type="email" required value="admin@school.local" />
  <label>Password</label><input name="password" type="password" required value="admin123" />
  <button type="submit">Sign in</button>
  <p class="muted">SEED_DATA demo accounts — see README.</p>
</form>
<script>
document.getElementById("f").onsubmit = async function (e) {
  e.preventDefault();
  const fd = new FormData(e.target);
  const r = await window.api("/api/auth/login", { method: "POST", body: { email: fd.get("email"), password: fd.get("password") } });
  if (!r.ok) { window.showFlash(r.data.error || "Login failed", "err"); return; }
  localStorage.setItem("sms_token", r.data.token);
  location.href = "/dashboard.html";
};
</script>`,
      ),
    },
    {
      path: "public/dashboard.html",
      content: htmlPage(
        "Dashboard",
        "dashboard",
        `<p class="muted" id="roleline"></p>
<div class="grid" id="stats"><div class="card">Loading…</div></div>
<p class="muted">Role dashboards share this page; widgets depend on <code>/api/dashboard</code> and the signed-in role.</p>
<script>
(async function () {
  const user = await window.requireAuth();
  if (!user) return;
  document.getElementById("roleline").textContent = user.role + " dashboard";
  const r = await window.api("/api/dashboard");
  const el = document.getElementById("stats");
  if (!r.ok) { el.innerHTML = '<div class="card error">Could not load dashboard</div>'; return; }
  const d = r.data;
  el.innerHTML = ["Students|" + d.students, "Teachers|" + d.teachers, "Classes|" + d.classes, "Attendance today|" + d.attendanceToday]
    .map(function (s) { const p = s.split("|"); return '<div class="card"><div class="muted">' + p[0] + "</div><strong>" + p[1] + "</strong></div>"; })
    .join("");
})();
</script>`,
      ),
    },
    {
      path: "public/students.html",
      content: htmlPage(
        "Students",
        "students",
        `<p><a class="btn" href="/student-form.html">Add student</a></p>
<div id="state" class="muted">Loading…</div>
<table id="tbl" class="hidden"><thead><tr><th>Name</th><th>Email</th><th>Grade</th><th></th></tr></thead><tbody></tbody></table>
<script>
(async function () {
  const r = await window.api("/api/students");
  const st = document.getElementById("state");
  if (!r.ok) { st.textContent = r.data.error || "Error loading students"; st.className = "error"; return; }
  const items = r.data.items || [];
  if (!items.length) { st.textContent = "No students yet."; st.className = "empty"; return; }
  st.className = "hidden";
  const tbl = document.getElementById("tbl");
  tbl.classList.remove("hidden");
  tbl.querySelector("tbody").innerHTML = items.map(function (s) {
    return "<tr><td>" + s.firstName + " " + s.lastName + "</td><td>" + (s.email || "") + "</td><td>" + (s.grade || "") +
      '</td><td><a href="/student-profile.html?id=' + s.id + '">Open</a> · <a href="/student-form.html?id=' + s.id + '">Edit</a></td></tr>';
  }).join("");
})();
</script>`,
      ),
    },
    {
      path: "public/student-profile.html",
      content: htmlPage(
        "Student profile",
        "students",
        `<div id="state" class="muted">Loading…</div>
<div id="body" class="hidden card"></div>
<script>
(async function () {
  const id = new URLSearchParams(location.search).get("id");
  const r = await window.api("/api/students/" + id);
  const st = document.getElementById("state");
  if (!r.ok) { st.textContent = "Student not found"; st.className = "error"; return; }
  st.className = "hidden";
  const s = r.data;
  const el = document.getElementById("body");
  el.classList.remove("hidden");
  el.innerHTML = "<p><strong>" + s.firstName + " " + s.lastName + "</strong></p><p>" + (s.email || "") +
    "</p><p>Grade " + (s.grade || "—") + "</p><p><a href='/student-form.html?id=" + s.id + "'>Edit</a></p>";
})();
</script>`,
      ),
    },
    {
      path: "public/student-form.html",
      content: htmlPage(
        "Student form",
        "students",
        `<form class="card" id="f">
  <label>First name</label><input name="firstName" required />
  <label>Last name</label><input name="lastName" required />
  <label>Email</label><input name="email" type="email" />
  <label>Grade</label><input name="grade" />
  <button type="submit">Save</button>
</form>
<script>
(async function () {
  const id = new URLSearchParams(location.search).get("id");
  if (id) {
    const r = await window.api("/api/students/" + id);
    if (r.ok) {
      const f = document.getElementById("f");
      f.firstName.value = r.data.firstName; f.lastName.value = r.data.lastName;
      f.email.value = r.data.email || ""; f.grade.value = r.data.grade || "";
    }
  }
  document.getElementById("f").onsubmit = async function (e) {
    e.preventDefault();
    const fd = new FormData(e.target);
    const body = { firstName: fd.get("firstName"), lastName: fd.get("lastName"), email: fd.get("email"), grade: fd.get("grade") };
    const r = id
      ? await window.api("/api/students/" + id, { method: "PUT", body })
      : await window.api("/api/students", { method: "POST", body });
    if (!r.ok) { window.showFlash(r.data.error || "Save failed", "err"); return; }
    location.href = "/students.html";
  };
})();
</script>`,
      ),
    },
    {
      path: "public/teachers.html",
      content: htmlPage(
        "Teachers",
        "teachers",
        `<p><a class="btn" href="/teacher-form.html">Add teacher</a></p>
<div id="state" class="muted">Loading…</div>
<table id="tbl" class="hidden"><thead><tr><th>Name</th><th>Subject</th><th></th></tr></thead><tbody></tbody></table>
<script>
(async function () {
  const r = await window.api("/api/teachers");
  const st = document.getElementById("state");
  if (!r.ok) { st.textContent = r.data.error || "Error"; st.className = "error"; return; }
  const items = r.data.items || [];
  if (!items.length) { st.textContent = "No teachers yet."; st.className = "empty"; return; }
  st.className = "hidden";
  const tbl = document.getElementById("tbl");
  tbl.classList.remove("hidden");
  tbl.querySelector("tbody").innerHTML = items.map(function (t) {
    return "<tr><td>" + t.firstName + " " + t.lastName + "</td><td>" + (t.subject || "") +
      '</td><td><a href="/teacher-profile.html?id=' + t.id + '">Open</a> · <a href="/teacher-form.html?id=' + t.id + '">Edit</a></td></tr>';
  }).join("");
})();
</script>`,
      ),
    },
    {
      path: "public/teacher-profile.html",
      content: htmlPage(
        "Teacher profile",
        "teachers",
        `<div id="state" class="muted">Loading…</div><div id="body" class="hidden card"></div>
<script>
(async function () {
  const id = new URLSearchParams(location.search).get("id");
  const r = await window.api("/api/teachers/" + id);
  const st = document.getElementById("state");
  if (!r.ok) { st.textContent = "Not found"; st.className = "error"; return; }
  st.className = "hidden";
  const t = r.data; const el = document.getElementById("body"); el.classList.remove("hidden");
  el.innerHTML = "<p><strong>" + t.firstName + " " + t.lastName + "</strong></p><p>" + (t.subject || "") + "</p>";
})();
</script>`,
      ),
    },
    {
      path: "public/teacher-form.html",
      content: htmlPage(
        "Teacher form",
        "teachers",
        `<form class="card" id="f">
  <label>First name</label><input name="firstName" required />
  <label>Last name</label><input name="lastName" required />
  <label>Email</label><input name="email" type="email" />
  <label>Subject</label><input name="subject" />
  <button type="submit">Save</button>
</form>
<script>
(async function () {
  const id = new URLSearchParams(location.search).get("id");
  if (id) {
    const r = await window.api("/api/teachers/" + id);
    if (r.ok) {
      const f = document.getElementById("f");
      f.firstName.value = r.data.firstName; f.lastName.value = r.data.lastName;
      f.email.value = r.data.email || ""; f.subject.value = r.data.subject || "";
    }
  }
  document.getElementById("f").onsubmit = async function (e) {
    e.preventDefault();
    const fd = new FormData(e.target);
    const body = { firstName: fd.get("firstName"), lastName: fd.get("lastName"), email: fd.get("email"), subject: fd.get("subject") };
    const r = id
      ? await window.api("/api/teachers/" + id, { method: "PUT", body })
      : await window.api("/api/teachers", { method: "POST", body });
    if (!r.ok) { window.showFlash(r.data.error || "Save failed", "err"); return; }
    location.href = "/teachers.html";
  };
})();
</script>`,
      ),
    },
    {
      path: "public/attendance.html",
      content: htmlPage(
        "Attendance",
        "attendance",
        `<p><a class="btn" href="/attendance-mark.html">Mark attendance</a></p>
<div id="state" class="muted">Loading…</div>
<table id="tbl" class="hidden"><thead><tr><th>Date</th><th>Student</th><th>Status</th></tr></thead><tbody></tbody></table>
<script>
(async function () {
  const [att, stu] = await Promise.all([window.api("/api/attendance"), window.api("/api/students")]);
  const st = document.getElementById("state");
  if (!att.ok) { st.textContent = att.data.error || "Error"; st.className = "error"; return; }
  const students = {};
  (stu.data.items || []).forEach(function (s) { students[s.id] = s.firstName + " " + s.lastName; });
  const items = att.data.items || [];
  if (!items.length) { st.textContent = "No attendance records yet."; st.className = "empty"; return; }
  st.className = "hidden";
  const tbl = document.getElementById("tbl");
  tbl.classList.remove("hidden");
  tbl.querySelector("tbody").innerHTML = items.map(function (a) {
    return "<tr><td>" + a.date + "</td><td>" + (students[a.studentId] || a.studentId) + "</td><td>" + a.status + "</td></tr>";
  }).join("");
})();
</script>`,
      ),
    },
    {
      path: "public/attendance-mark.html",
      content: htmlPage(
        "Mark attendance",
        "attendance",
        `<form class="card" id="f">
  <label>Student</label><select name="studentId" required></select>
  <label>Date</label><input name="date" type="date" required />
  <label>Status</label><select name="status"><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option></select>
  <button type="submit">Save</button>
  <p class="muted">Teachers and admins only. Students who call POST /api/attendance receive 403.</p>
</form>
<script>
(async function () {
  const r = await window.api("/api/students");
  const sel = document.querySelector("[name=studentId]");
  (r.data.items || []).forEach(function (s) {
    const o = document.createElement("option"); o.value = s.id; o.textContent = s.firstName + " " + s.lastName; sel.appendChild(o);
  });
  document.querySelector("[name=date]").value = new Date().toISOString().slice(0, 10);
  document.getElementById("f").onsubmit = async function (e) {
    e.preventDefault();
    const fd = new FormData(e.target);
    const res = await window.api("/api/attendance", { method: "POST", body: { studentId: fd.get("studentId"), date: fd.get("date"), status: fd.get("status") } });
    if (!res.ok) { window.showFlash(res.data.error || "Forbidden", "err"); return; }
    location.href = "/attendance.html";
  };
})();
</script>`,
      ),
    },
    {
      path: "public/classes.html",
      content: htmlPage(
        "Classes",
        "classes",
        `<div id="state" class="muted">Loading…</div>
<div id="list"></div>
<script>
(async function () {
  const r = await window.api("/api/classes");
  const st = document.getElementById("state");
  if (!r.ok) { st.textContent = "Error"; st.className = "error"; return; }
  const items = r.data.items || [];
  if (!items.length) { st.textContent = "No classes yet."; st.className = "empty"; return; }
  st.className = "hidden";
  document.getElementById("list").innerHTML = items.map(function (c) {
    return '<div class="card"><strong>' + c.name + " " + (c.section || "") + "</strong><p class='muted'>Grade " + (c.grade || "—") + "</p></div>";
  }).join("");
})();
</script>`,
      ),
    },
    {
      path: "test/rbac.test.js",
      content: `import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { canAccess, ROLES, listPermissions } from "../src/rbac.js";

describe("school RBAC", () => {
  it("defines four roles", () => {
    assert.deepEqual(ROLES, ["Admin", "Teacher", "Student", "Parent"]);
  });
  it("admin can manage students", () => {
    assert.equal(canAccess("Admin", "manage_students"), true);
  });
  it("student cannot manage attendance", () => {
    assert.equal(canAccess("Student", "manage_attendance"), false);
  });
  it("teacher can manage attendance", () => {
    assert.equal(canAccess("Teacher", "manage_attendance"), true);
    assert.ok(listPermissions("Teacher").includes("manage_attendance"));
  });
});
`,
    },
    {
      path: "test/auth.test.js",
      content: `import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { hashPassword, verifyPassword, signToken, verifyToken } from "../src/auth.js";

describe("auth", () => {
  it("hashes and verifies passwords", () => {
    const h = hashPassword("secret");
    assert.equal(verifyPassword("secret", h), true);
    assert.equal(verifyPassword("nope", h), false);
  });
  it("signs and verifies session tokens", () => {
    const t = signToken({ userId: "u1", role: "Admin" });
    const p = verifyToken(t);
    assert.equal(p.userId, "u1");
    assert.equal(verifyToken("bad"), null);
  });
});
`,
    },
    {
      path: "test/students.test.js",
      content: `import { describe, it, before } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:os";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createStore } from "../src/store.js";
import { createHandler } from "../src/routes.js";
import http from "node:http";

function listen(handler) {
  const server = http.createServer(handler);
  return new Promise((resolve) => {
    server.listen(0, "127.0.0.1", () => {
      const port = server.address().port;
      resolve({ server, port });
    });
  });
}

async function req(port, path, opts) {
  const res = await fetch("http://127.0.0.1:" + port + path, {
    method: (opts && opts.method) || "GET",
    headers: Object.assign({ "Content-Type": "application/json" }, (opts && opts.headers) || {}),
    body: opts && opts.body ? JSON.stringify(opts.body) : undefined,
  });
  return { status: res.status, data: await res.json() };
}

describe("students API", () => {
  let port, server, token;
  before(async () => {
    const db = join(mkdtempSync(join(tmpdir(), "sms-")), "db.json");
    const store = createStore(db);
    const started = await listen(createHandler(store));
    server = started.server;
    port = started.port;
    const login = await req(port, "/api/auth/login", {
      method: "POST",
      body: { email: "admin@school.local", password: "admin123" },
    });
    token = login.data.token;
  });
  it("lists students and creates one that persists", async () => {
    const auth = { Authorization: "Bearer " + token };
    const created = await req(port, "/api/students", {
      method: "POST",
      headers: auth,
      body: { firstName: "Nia", lastName: "New", email: "nia@school.local", grade: "7" },
    });
    assert.equal(created.status, 201);
    const list = await req(port, "/api/students", { headers: auth });
    assert.equal(list.status, 200);
    assert.ok(list.data.items.some((s) => s.email === "nia@school.local"));
    const one = await req(port, "/api/students/" + created.data.id, { headers: auth });
    assert.equal(one.data.firstName, "Nia");
    server.close();
  });
});
`,
    },
    {
      path: "test/attendance.test.js",
      content: `import { describe, it, before } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, tmpdir } from "node:os";
import { join } from "node:path";
import { createStore } from "../src/store.js";
import { createHandler } from "../src/routes.js";
import http from "node:http";

function listen(handler) {
  const server = http.createServer(handler);
  return new Promise((resolve) => {
    server.listen(0, "127.0.0.1", () => resolve({ server, port: server.address().port }));
  });
}
async function req(port, path, opts) {
  const res = await fetch("http://127.0.0.1:" + port + path, {
    method: (opts && opts.method) || "GET",
    headers: Object.assign({ "Content-Type": "application/json" }, (opts && opts.headers) || {}),
    body: opts && opts.body ? JSON.stringify(opts.body) : undefined,
  });
  return { status: res.status, data: await res.json() };
}

describe("attendance authorization", () => {
  let port, server, teacherToken, studentToken, studentId;
  before(async () => {
    const db = join(mkdtempSync(join(tmpdir(), "sms-")), "db.json");
    const store = createStore(db);
    studentId = store.all("students")[0].id;
    const started = await listen(createHandler(store));
    server = started.server;
    port = started.port;
    teacherToken = (await req(port, "/api/auth/login", {
      method: "POST",
      body: { email: "teacher@school.local", password: "teacher123" },
    })).data.token;
    studentToken = (await req(port, "/api/auth/login", {
      method: "POST",
      body: { email: "student@school.local", password: "student123" },
    })).data.token;
  });
  it("teacher can mark attendance", async () => {
    const r = await req(port, "/api/attendance", {
      method: "POST",
      headers: { Authorization: "Bearer " + teacherToken },
      body: { studentId, date: "2026-08-30", status: "present" },
    });
    assert.equal(r.status, 200);
    assert.equal(r.data.status, "present");
  });
  it("student cannot mark attendance via the API", async () => {
    const r = await req(port, "/api/attendance", {
      method: "POST",
      headers: { Authorization: "Bearer " + studentToken },
      body: { studentId, date: "2026-08-30", status: "absent" },
    });
    assert.equal(r.status, 403);
    server.close();
  });
});
`,
    },
  ];
}
