import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: '2rem' }}>
        <h1>Welcome to My App</h1>
        <p>This is the home page.</p>
        <Link href="/about">
          <a>Go to About page</a>
        </Link>
      </main>
    </>
  )
}

export default HomePage
